export const UserConstants = {
    FULL_NAME: 'Full Name',
    EMAIL_ADDRESS: 'Email Address',
    SMOKING_PATTERN: 'Smoking Pattern',
    LOGOUT: 'Logout',
    DELETE_PROFILE: 'Delete Profile',
    ARE_YOU_SURE_TO_DELETE_YOUR_PROFILE: 'Are you sure to delete your profile',
    NORMAL_TYPE: 'Normal (3 - 5 times per week)',
    AVERAGE_TYPE: 'Average (10 - 15 times per week)',
    EXTREME_TYPE: 'Extereme (20 - 25 times per week)',
    OTHER: 'Other',
    ENTER_EMAIL: "Enter your Email Address",
    ENTER_PASSWORD: "Enter your Password",
    ENTER_NAME: "Enter your Full Name",
    CONFIRM_PASSWORD: "Confirm your Password",
    HOW_OFTEN_DO_YOU_SMOKE: "How often do you smoke?",
    LOGIN: "Login",
    REGISTER: "Register",
    FORGOT_PASSWORD: "Forgot Password ?",
    PLACEHOLDER_EMAIL: "example@gmail.com",
    PLACEHOLDER_NAME: "your name",
    SUBMIT: "Submit",
    PRIVACY_POLICY: "Click here to see the Privacy Policy",
    TERMS_CONDITIONS: "By Clicking on Submit, you agree to our terms and conditions",
    QUICK_GUIDE: "This app will help the user to stop smoking, by providing some challenges. User needs to register into the app by providing some details, to use the app. User can Login to the application using email address and password."
}